# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ayltai/circleci-openjdk-node:jdk8-node11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm install --save-dev
      - run: npm rebuild
      - run:
          command: |
            node --version
            npm --version
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-cli firebase-tools

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/firebase/emulators/
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run firebase emulator
          command: ./firebase-cli/node_modules/.bin/firebase emulators:start --only firestore
          background: true

      # run tests!
      - run: npm run test